### ISSUE TITLE
switch case or escaped quotes issue 

### ISSUE THREAD

**Issue by werebear73** [miconda/atom-extensions#3]
The following code doesn't seem to format correctly.  
![Capture_Atom_Kamailio_Escaped_Double_Quotes](https://user-images.githubusercontent.com/3290150/65686531-794f5000-e02a-11e9-97d0-c8cdddd5ad4e.PNG)

**Comment by werebear73** [comment]
Daniel,

I am not very familiar with GIT, but here is the fix.

Replace :

	{
		'begin': '([^\\\\]")'
		'end': '"'
		'name': 'string.quoted.double.kamailio'
	}

With:

	{
    'begin': '\"'
    'beginCaptures':
        '0':
            'name': 'punctuation.definition.string.begin.kamailio'
    'end': '\"'
    'endCaptures':
        '0':
            'name': 'punctuation.definition.string.end.kamailio'
    'name': 'string.quoted.double.kamailio'
    'patterns': [
        {
            'match': '\\"'
            'name': 'constant.character.escape.kamailio'
        }
    ]
	}


in the CSON file.  I stole this from @50Wliu in the PHP Language group (https://github.com/atom/language-php/pull/330/commits)

Thanks,

Sam

**Comment by werebear73** [comment]
See the fork below for the changes too

https://github.com/werebear73/atom-extensions

**Comment by werebear73** [comment]
See the fork below for the changes too

https://github.com/werebear73/atom-extensions

**Comment by miconda** [comment]
I forgot to check this issue, I just noticed and merged the pull request about escaped quotes. Is the switch case still an issue?

**Comment by werebear73** [comment]
Yes, this turned out to be the solution to that issue.

**Comment by miconda** [comment]
OK, thanks, I will close this one then.
